export const seedData = [
  {
    key: crypto.randomUUID(),
    title: "Shoe A",
    sizes: ["8.0", "8.5", "9.0"],
    price: "100.00",
    styleId: crypto.randomUUID(),
    color: ["Blanc Optique"],
    material: "Leather",
    imageUrl: "https://sellyoursole.s3.amazonaws.com/Black+Kicks.jpeg",
    details: [
      "10 High Top Sneaker",
      "Leather Upper",
      "Perforated and smooth leather panels",
      "Saint Laurent and SL/10H-debossed padded ankle",
      "SL/10H debossed at side",
      "Leather lining",
      "Leather Sole",
    ],
  },
  {
    key: crypto.randomUUID(),
    title: "Shoe B",
    sizes: ["8.0", "8.5", "9.0"],
    price: "100.00",
    styleId: crypto.randomUUID(),
    color: ["Blanc Optique"],
    material: "Leather",
    imageUrl: "https://sellyoursole.s3.amazonaws.com/FallOffKicks.jpeg",
    details: [
      "10 High Top Sneaker",
      "Leather Upper",
      "Perforated and smooth leather panels",
      "Saint Laurent and SL/10H-debossed padded ankle",
      "SL/10H debossed at side",
      "Leather lining",
      "Leather Sole",
    ],
  },
  {
    key: crypto.randomUUID(),
    title: "Shoe C",
    sizes: ["8.0", "8.5", "9.0"],
    price: "100.00",
    styleId: crypto.randomUUID(),
    color: ["Blanc Optique"],
    material: "Leather",
    imageUrl: "https://sellyoursole.s3.amazonaws.com/HangOffKicks.jpeg",
    details: [
      "10 High Top Sneaker",
      "Leather Upper",
      "Perforated and smooth leather panels",
      "Saint Laurent and SL/10H-debossed padded ankle",
      "SL/10H debossed at side",
      "Leather lining",
      "Leather Sole",
    ],
  },
  {
    key: crypto.randomUUID(),
    title: "Shoe D",
    sizes: ["8.0", "8.5", "9.0"],
    price: "100.00",
    styleId: crypto.randomUUID(),
    color: ["Blanc Optique"],
    material: "Leather",
    imageUrl: "https://sellyoursole.s3.amazonaws.com/Jordan+Ones.jpeg",
    details: [
      "10 High Top Sneaker",
      "Leather Upper",
      "Perforated and smooth leather panels",
      "Saint Laurent and SL/10H-debossed padded ankle",
      "SL/10H debossed at side",
      "Leather lining",
      "Leather Sole",
    ],
  },
  {
    key: crypto.randomUUID(),
    title: "Shoe E",
    sizes: ["8.0", "8.5", "9.0"],
    price: "100.00",
    styleId: crypto.randomUUID(),
    color: ["Blanc Optique"],
    material: "Leather",
    imageUrl: "https://sellyoursole.s3.amazonaws.com/LowTopKicks.jpeg",
    details: [
      "10 High Top Sneaker",
      "Leather Upper",
      "Perforated and smooth leather panels",
      "Saint Laurent and SL/10H-debossed padded ankle",
      "SL/10H debossed at side",
      "Leather lining",
      "Leather Sole",
    ],
  },
  {
    key: crypto.randomUUID(),
    title: "Shoe F",
    sizes: ["8.0", "8.5", "9.0"],
    price: "100.00",
    styleId: crypto.randomUUID(),
    color: ["Blanc Optique"],
    material: "Leather",
    imageUrl: "https://sellyoursole.s3.amazonaws.com/Soft+Palette+Kicks.jpeg",
    details: [
      "10 High Top Sneaker",
      "Leather Upper",
      "Perforated and smooth leather panels",
      "Saint Laurent and SL/10H-debossed padded ankle",
      "SL/10H debossed at side",
      "Leather lining",
      "Leather Sole",
    ],
  },
];
